version: "3.7"

services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ACCESS_KEY=TESTKEY
      - MINIO_SECRET_KEY=TESTSECRET
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 35s
      timeout: 20s
      retries: 3
    command: server --compat /data

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - "3000:3000"

  localstack:
    image: localstack/localstack:0.11.1
    ports:
      - '4569:4569'
    environment:
      - SERVICES=dynamodb
 
  localstack_secrets_manager:
    image: localstack/localstack:0.11.1
    ports:
      - '4584:4584'
    environment:
      - SERVICES=secretsmanager
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - DEFAULT_REGION=us-east-2

  redis:
    image: redis
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5
